#!/usr/bin/env bash
# Lifecycle helper for the LOCAL Supabase stack.
#
#   ./scripts/local-supabase.sh start    # spin up Docker stack, write ../.env.local.dev
#   ./scripts/local-supabase.sh stop     # tear down
#   ./scripts/local-supabase.sh reset    # wipe + re-run migrations + seed
#   ./scripts/local-supabase.sh env      # just (re)write .env.local.dev from running stack
#   ./scripts/local-supabase.sh status   # show URLs / keys
#
# Requires `supabase` on PATH (or at ~/bin/supabase) and Docker running.
set -euo pipefail
cd "$(dirname "$0")/.."

SUPABASE_BIN="$(command -v supabase || true)"
if [[ -z "$SUPABASE_BIN" && -x "$HOME/bin/supabase" ]]; then SUPABASE_BIN="$HOME/bin/supabase"; fi
if [[ -z "$SUPABASE_BIN" ]]; then
  echo "ERROR: supabase CLI not found. Install via 'brew install supabase/tap/supabase' or place the binary in ~/bin." >&2
  exit 1
fi

write_env() {
  # `supabase status -o env` prints shell-style env assignments
  local out
  out="$("$SUPABASE_BIN" status -o env 2>/dev/null)"
  if [[ -z "$out" ]]; then
    echo "WARN: stack not running, can't write env file." >&2
    return 1
  fi
  local url anon
  url="$(printf '%s\n' "$out"  | sed -nE 's/^API_URL="([^"]+)".*/\1/p' | head -1)"
  anon="$(printf '%s\n' "$out" | sed -nE 's/^ANON_KEY="([^"]+)".*/\1/p' | head -1)"
  if [[ -z "$url" || -z "$anon" ]]; then
    echo "ERROR: couldn't parse API_URL/ANON_KEY from 'supabase status -o env'." >&2
    printf '%s\n' "$out" >&2
    return 1
  fi
  cat > .env.local.dev <<EOF
# Generated by scripts/local-supabase.sh — do not commit.
EXPO_PUBLIC_SUPABASE_URL=$url
EXPO_PUBLIC_SUPABASE_KEY=$anon
EOF
  echo "wrote .env.local.dev"
}

case "${1:-status}" in
  start)
    "$SUPABASE_BIN" start
    write_env || true
    echo
    echo "▶ Local Supabase ready."
    echo "  Studio:    $("$SUPABASE_BIN" status -o env | sed -nE 's/^STUDIO_URL="([^"]+)".*/\1/p')"
    echo "  Sign in:   popescut94@gmail.com / localdev"
    ;;
  stop)
    "$SUPABASE_BIN" stop
    ;;
  reset)
    "$SUPABASE_BIN" db reset
    write_env || true
    ;;
  env)
    write_env
    ;;
  status)
    "$SUPABASE_BIN" status
    ;;
  *)
    echo "usage: $0 {start|stop|reset|env|status}" >&2
    exit 2
    ;;
esac
